
include(ExternalProject)

set(ONEMATH_SOURCE_DIR  ${CMAKE_BINARY_DIR}/oneMath-src)
set(ONEMATH_BINARY_DIR  ${CMAKE_BINARY_DIR}/oneMath-build)
set(ONEMATH_INSTALL_DIR ${CMAKE_BINARY_DIR}/deps/oneMath)
set(ONEMATH_INCLUDE_DIR ${ONEMATH_INSTALL_DIR}/include)
set(ONEMATH_LIB_DIR ${ONEMATH_INSTALL_DIR}/lib)
set(ONEMATH_LIB ${ONEMATH_LIB_DIR}/libonemath.so)

ExternalProject_Add(
  oneMath_project
  GIT_REPOSITORY https://github.com/uxlfoundation/oneMath.git
  GIT_TAG        "develop"
  SOURCE_DIR     ${ONEMATH_SOURCE_DIR}
  BINARY_DIR     ${ONEMATH_BINARY_DIR}

  CMAKE_ARGS
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  -DCMAKE_GENERATOR=${CMAKE_GENERATOR}
  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${ONEMATH_INSTALL_DIR}
  -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-rpath=${ONEMKL_LIB_DIR}"
  -DENABLE_MKLCPU_BACKEND=OFF
  -DENABLE_MKLGPU_BACKEND=ON
  -DBUILD_FUNCTIONAL_TESTS=OFF
  -DBUILD_EXAMPLES=OFF
  -DBUILD_DOC=OFF
  -DTARGET_DOMAINS=rng

  BUILD_BYPRODUCTS ${ONEMATH_LIB}
)

add_library(oneMath SHARED IMPORTED)
add_dependencies(oneMath oneMath_project)
